#!/bin/bash

elev=$(echo $1 | tr -cd '[:digit:].-')
unit=$(echo $2 | tr -cd '[:alpha:].-')

if [ $unit = "meters" ]; then
    echo
    echo "meters"
    echo
    unitabr="m"
    if ! awk "BEGIN{ exit ($elev > 8448) }" || ! awk "BEGIN{ exit ($elev < -1000) }"; then
        echo
        echo "Invalid elevation: $elev"
        echo "Elevation must be between -1000 and 8448"
        echo
        echo "Usage:"
        echo "readsb-set-elevation 1440 meters"
        echo
        exit 1
    fi
fi

if [ $unit = "feet" ]; then
    echo
    echo "feet"
    echo
    unitabr="ft"
    if ! awk "BEGIN{ exit ($elev > 18000) }" || ! awk "BEGIN{ exit ($elev < -10000) }"; then
        echo
        echo "Invalid elevation: $elev"
        echo "Elevation must be between -10000 and 18000"
        echo
        echo "Usage:"
        echo "readsb-set-location 1440 feet"
        echo
        exit 1
    fi
fi

echo
echo "setting elevation: $elev$unitabr"
echo
if ! grep -e '--alt' /etc/default/readsb &>/dev/null; then sed -i -e 's/DECODER_OPTIONS="/DECODER_OPTIONS="--alt -8448m /' /etc/default/readsb; fi

# --alt\s*.?[0-9]*.?[0-9]ft
if [ $unit = "feet" ]; then

   sed -i -E -e "s/--alt .?[0-9]*.?[0-9](ft|m)* /--alt $elev$unitabr /" /etc/default/readsb
fi

if [ $unit = "meters" ]; then
   sed -i -E -e "s/--alt .?[0-9]*.?[0-9](ft|m)* /--alt $elev$unitabr /" /etc/default/readsb
fi

systemctl restart readsb
